In [10]:
import numpy as np
import pandas as pd
from policyengine_us import Microsimulation
from policyengine_core.reforms import Reform

In [11]:
reform = Reform.from_dict(
    {
        "gov.contrib.repeal_state_dependent_exemptions.in_effect": {
            "2024-01-01.2100-12-31": True
        }
    },
    country_id="us",
)


baseline = Microsimulation(dataset="pooled_3_year_cps_2023")
reformed = Microsimulation(reform=reform, dataset="pooled_3_year_cps_2023")
baseline_income = baseline.calculate("household_net_income", period=2024)
reformed_income = reformed.calculate("household_net_income", period=2024)
difference_income = reformed_income - baseline_income

In [12]:
# Get state codes
state_code = baseline.calculate("state_code", period=2024)

# Get household weights for accurate aggregation
weights = baseline.calculate("household_weight", period=2024)

# Create a DataFrame with the results
results_df = pd.DataFrame(
    {"state_code": state_code, "income_change": difference_income, "weight": weights}
)

# Calculate state-level statistics
state_impacts = (
    results_df.groupby("state_code")
    .agg(
        {
            "income_change": lambda x: np.average(
                x, weights=results_df.loc[x.index, "weight"]
            ),
            "weight": "sum",
        }
    )
    .reset_index()
)

In [13]:
# Calculate total income impact
total_impact_by_state = (
    results_df.groupby("state_code")
    .apply(lambda x: np.sum(x["income_change"] * x["weight"]))
    .reset_index(name="total_income_impact")
)

# Merge total impact into main results
state_impacts = state_impacts.merge(total_impact_by_state, on="state_code")

# Add households affected
state_impacts["households_affected"] = (
    results_df[results_df["income_change"] != 0]
    .groupby("state_code")["weight"]
    .sum()
    .reindex(state_impacts["state_code"])
    .fillna(0)
)

# Calculate percentage of households affected
state_impacts["percent_households_affected"] = (
    state_impacts["households_affected"] / state_impacts["weight"] * 100
)

# Format the results
state_impacts["avg_income_change"] = state_impacts["income_change"].round(2)
state_impacts["total_income_impact"] = state_impacts["total_income_impact"].round(0)
state_impacts["households_affected"] = state_impacts["households_affected"].round(0)
state_impacts["percent_households_affected"] = state_impacts[
    "percent_households_affected"
].round(2)
state_impacts["weight"] = state_impacts["weight"].round(0)

# Sort by total impact
state_impacts_sorted = state_impacts.sort_values("total_income_impact")

# Rename columns for clarity
state_impacts_sorted = state_impacts_sorted.rename(
    columns={
        "weight": "total_households",
        "avg_income_change": "avg_income_change_per_household",
        "total_income_impact": "total_state_income_impact",
    }
)

# Calculate national totals
national_totals = pd.DataFrame(
    {
        "state_code": ["TOTAL"],
        "total_households": [state_impacts_sorted["total_households"].sum()],
        "avg_income_change_per_household": [
            (
                state_impacts_sorted["total_state_income_impact"].sum()
                / state_impacts_sorted["total_households"].sum()
            )
        ],
        "total_state_income_impact": [
            state_impacts_sorted["total_state_income_impact"].sum()
        ],
        "households_affected": [state_impacts_sorted["households_affected"].sum()],
        "percent_households_affected": [
            (
                state_impacts_sorted["households_affected"].sum()
                / state_impacts_sorted["total_households"].sum()
                * 100
            )
        ],
    }
)

# Combine state results with national totals
final_results = pd.concat([state_impacts_sorted, national_totals])

# Display results
print("\nState-by-State Impact Analysis:")
print(
    final_results[
        [
            "state_code",
            "total_households",
            "avg_income_change_per_household",
            "total_state_income_impact",
            "households_affected",
            "percent_households_affected",
        ]
    ].to_string()
)

State-by-State Impact Analysis:
   state_code  total_households  avg_income_change_per_household  total_state_income_impact  households_affected  percent_households_affected
4          CA        14365824.0                      -161.660004              -2.322313e+09                  NaN                          NaN
22         MI         4228719.0                      -113.089996              -4.782457e+08                  NaN                          NaN
10         GA         4348380.0                       -94.570000              -4.112280e+08                  NaN                          NaN
23         MN         2344873.0                      -166.809998              -3.911444e+08                  NaN                          NaN
14         IL         5187204.0                       -61.619999              -3.196205e+08                  NaN                          NaN
34         NY         7896529.0                       -28.510000              -2.251366e+08                  NaN                          NaN
40         SC         2221951.0                      -100.739998              -2.238372e+08                  NaN                          NaN
31         NJ         3578201.0                       -44.169998              -1.580493e+08                  NaN                          NaN
20         MD         2319566.0                       -55.279999              -1.282159e+08                  NaN                          NaN
35         OH         4992720.0                       -23.680000              -1.182335e+08                  NaN                          NaN
45         VA         3492310.0                       -26.049999              -9.097714e+07                  NaN                          NaN
29         NE          799766.0                       -97.879997              -7.828219e+07                  NaN                          NaN
15         IN         2804274.0                       -18.070000              -5.068625e+07                  NaN                          NaN
36         OK         1626192.0                       -23.270000              -3.784758e+07                  NaN                          NaN
39         RI          463160.0                       -79.510002              -3.682365e+07                  NaN                          NaN
25         MS         1201572.0                       -29.100000              -3.496678e+07                  NaN                          NaN
46         VT          292460.0                      -107.150002              -3.133655e+07                  NaN                          NaN
12         IA         1364209.0                       -22.860001              -3.118891e+07                  NaN                          NaN
49         WV          750805.0                       -39.840000              -2.991399e+07                  NaN                          NaN
1          AL         2120076.0                       -12.520000              -2.653426e+07                  NaN                          NaN
11         HI          500921.0                       -46.590000              -2.333804e+07                  NaN                          NaN
18         LA         1870034.0                        -9.250000              -1.730031e+07                  NaN                          NaN
19         MA         2817993.0                        -0.360000              -1.003168e+06                  NaN                          NaN
16         KS         1215639.0                        -0.040000              -4.977200e+04                  NaN                          NaN
38         PA         5365676.0                         0.000000               0.000000e+00                  NaN                          NaN
42         TN         2986816.0                         0.000000               0.000000e+00                  NaN                          NaN
37         OR         1752219.0                         0.000000               0.000000e+00                  NaN                          NaN
43         TX        11362365.0                         0.000000               0.000000e+00                  NaN                          NaN
44         UT         1150286.0                         0.000000               0.000000e+00                  NaN                          NaN
47         WA         3185000.0                         0.000000               0.000000e+00                  NaN                          NaN
48         WI         2559938.0                         0.000000               0.000000e+00                  NaN                          NaN
41         SD          385189.0                         0.000000               0.000000e+00                  NaN                          NaN
33         NV         1265835.0                         0.000000               0.000000e+00                  NaN                          NaN
0          AK          275571.0                         0.000000               0.000000e+00                  NaN                          NaN
30         NH          591239.0                         0.000000               0.000000e+00                  NaN                          NaN
2          AR         1279007.0                         0.000000               0.000000e+00                  NaN                          NaN
3          AZ         2941938.0                         0.000000               0.000000e+00                  NaN                          NaN
5          CO         2440251.0                         0.000000               0.000000e+00                  NaN                          NaN
6          CT         1503523.0                         0.000000               0.000000e+00                  NaN                          NaN
7          DC          330109.0                         0.000000               0.000000e+00                  NaN                          NaN
8          DE          410404.0                         0.000000               0.000000e+00                  NaN                          NaN
32         NM          882902.0                         0.000000               0.000000e+00                  NaN                          NaN
9          FL         9323535.0                         0.000000               0.000000e+00                  NaN                          NaN
17         KY         1886632.0                         0.000000               0.000000e+00                  NaN                          NaN
21         ME          608698.0                         0.000000               0.000000e+00                  NaN                          NaN
24         MO         2570655.0                         0.000000               0.000000e+00                  NaN                          NaN
26         MT          494750.0                         0.000000               0.000000e+00                  NaN                          NaN
27         NC         4553814.0                         0.000000               0.000000e+00                  NaN                          NaN
28         ND          338181.0                         0.000000               0.000000e+00                  NaN                          NaN
13         ID          769370.0                         0.000000               0.000000e+00                  NaN                          NaN
50         WY          242744.0                         0.000000               0.000000e+00                  NaN                          NaN
0       TOTAL       134260032.0                       -39.224422              -5.266272e+09                  0.0                          0.0

In [14]:
final_results.to_csv("state_impacts_detailed.csv", index=False)